feat: migrate to typescript
twilio-labs/actions-sms pull request #7
Opened 2019-10-01 23:40 UTC by palaparthi

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

2019-10-01 23:47 UTC, dkundel commented on tsconfig.json
> +    "outDir": "./built",
Can we change this one to `./dist`?

2019-10-01 23:48 UTC, dkundel commented on tsconfig.json
> +    "./*"
let's move this to `./src` instead. So `./src/main.ts` and `./dist/main.js`

2019-10-02 19:26 UTC, palaparthi commented
Can you take a look and let me know if I am missing something. Thanks!

2019-10-04 00:02 UTC, merged

2023-01-17 04:46 UTC, KILDIAN requested changes
>